#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export JJCMD_NAME='Command-Line Tooling for Jay Jay';
export JJCMD_CODE='jjcmd';

export JJCMD_VERSION='0.1.127';
export JJCMD_VERSION_MAJOR='0';
export JJCMD_VERSION_MINOR='1';
export JJCMD_VERSION_PATCH='127';

export JJCMD_SVN_DATE='Date: 2025-04-06 04:58:53 +1000 (Sun, 06 Apr 2025)';
export JJCMD_SVN_REVISION='Revision: 152838279';
export JJCMD_SVN_AUTHOR='Author: jj5';

export JJCMD_GIT_DATE='2025-04-06 04:58:53 +1000 (Sun, 06 Apr 2025)';
