<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'JJCMD_NAME', "Jay Jay's Command-Line Tool" );
define( 'JJCMD_CODE', 'jjcmd' );

//define( 'JJCMD_VERSION', '0.1.377' );
define( 'JJCMD_VERSION_MAJOR', 0 );
define( 'JJCMD_VERSION_MINOR', 1 );
define( 'JJCMD_VERSION_PATCH', 1 );

define(
  'JJCMD_SVN_DATE',
  '$Date: 2025-02-22 08:48:40 +1100 (Sat, 22 Feb 2025) $'
);
define( 'JJCMD_SVN_REVISION', '$Revision: 55207851 $' );
define( 'JJCMD_SVN_AUTHOR', '$Author: jj5 $' );

define( 'JJCMD_GIT_DATE', '2025-02-22 08:48:40 +1100 (Sat, 22 Feb 2025)' );
